/**
 * _llm-markdown.ts — Pure MDX → agent-markdown transform (no Astro/Vite deps).
 *
 * Underscore prefix keeps this OUT of the route table; it is a helper imported
 * by the `[...slug].md.ts` endpoint. Kept pure (demo resolution is injected) so
 * it can be unit-tested without a running Vite/Astro pipeline.
 *
 * Goal: turn a human-facing `.mdx` doc page into a lean, self-contained Markdown
 * document that an AI agent can fetch in isolation. The critical job is
 * **inlining demo `<script>` blocks** — in the source MDX the runnable code lives
 * inside imported `.astro` demo components (`<IntroBasicDemo />`), so an agent that
 * only sees the MDX would get prose plus an opaque component tag. We resolve each
 * demo back to its `.astro` source and inline the script as a fenced code block.
 */

// #region Types

/**
 * Target framework for a framework-scoped agent corpus
 * (`llms-full-{framework}.txt`). `'vanilla'` keeps the plain TypeScript/JS/HTML
 * examples and drops the React/Vue/Angular adapter variants.
 */
export type Framework = 'vanilla' | 'react' | 'vue' | 'angular';

export interface AgentMarkdownOptions {
  /**
   * Resolve a demo `.astro` path (e.g. `demos/IntroBasicDemo.astro`) to its raw
   * source text, or `undefined` if it cannot be found.
   */
  resolveDemo: (relPath: string) => string | undefined;
  /**
   * Resolve a repo-relative demo-app source path (e.g.
   * `demos/vanilla/src/demos/employee-management/grid-config.ts`) to its raw
   * text, or `undefined` if not found. Drives the `<AgentSource paths="…" />`
   * directive, which inlines a full end-to-end reference implementation into the
   * agent corpus from the live demo's own source. When omitted, `<AgentSource>`
   * tags are stripped.
   */
  resolveSource?: (relPath: string) => string | undefined;
  /**
   * Return `true` if the given lowercase doc slug (e.g. `grid/getting-started`)
   * has a generated `.md` companion page. Used to rewrite internal HTML links to
   * their `.md` form so agents stay in the markdown graph. When omitted, internal
   * links are left untouched.
   */
  hasDoc?: (slug: string) => boolean;
  /**
   * Markdown to substitute for a `<CSSVariableReference />` widget tag (the theming
   * guide's live CSS-variable table). Generated by the endpoint from the shared
   * `CSS_VARIABLES` registry — see `cssVariableReferenceMarkdown` in `_llm-sources`.
   * Injected here so the transform need not import doc data and stay pure. When
   * omitted, the tag is stripped like any other non-demo widget.
   */
  cssVarReference?: string;
  /**
   * When set, produce a framework-scoped corpus: within framework tab groups
   * (those offering React/Vue/Angular alternatives), keep only the variant for
   * this framework and drop the rest. Neutral tab groups (e.g. npm/yarn/CDN) and
   * pages with no framework tabs are left untouched. When omitted, every tab
   * variant is kept.
   */
  frameworkFilter?: Framework;
  /**
   * Lowercase H2 heading texts whose whole section (the `## Heading` line through
   * everything up to the next `##`/`#`) is removed from the output. Used by the
   * `llms-full.txt` corpus builder to drop illustrative/navigational sections —
   * `## Demos`, `## Demo`, `## See Also` — that inline large demo `.astro` dumps
   * or pure link lists and carry no API truth, while keeping every API-bearing
   * section (Installation, Basic Usage, Configuration Options, Programmatic API,
   * Events, Keyboard Shortcuts). NOT passed by the per-page `.md` endpoint, so a
   * single-page fetch still includes its demos. Matched case-insensitively after
   * stripping any `[text](url)` link wrapper from the heading.
   */
  dropSections?: string[];
  /**
   * Inverse of `dropSections`: when set, the output keeps ONLY the page preamble
   * (everything before the first `##`) plus the listed H2 sections; every other
   * H2 section is removed. Used by the `llms-full.txt` corpus builder to demote
   * plugin pages to a compact "how to enable + basic usage" stub (intro +
   * `## Installation` + `## Basic Usage`), with the deep API (configuration
   * tables, events, methods) linked as a per-page `.md` companion rather than
   * inlined — the dominant corpus-size driver. NOT passed by the per-page `.md`
   * endpoint, so a single-page fetch still includes the full plugin API. Matched
   * case-insensitively after stripping any `[text](url)` link wrapper. Applied
   * after `dropSections`.
   */
  keepSections?: string[];
  /**
   * When `true`, bare demo components (`<DemoName />`) and `<ShowSource file>`
   * blocks are NOT inlined as code; each is replaced by a one-line pointer to the
   * page's `.md` companion (`demoPageUrl`). Used by the per-framework corpus
   * variants (`llms-full-{react,vue,angular}.txt`): the demo `.astro` sources are
   * vanilla-only (`queryGrid` + `HTMLElement` renderers), so inlining them into a
   * framework-scoped corpus contradicts that framework's "use components, not
   * HTMLElements" guidance. The framework-native snippet in the adjacent tab group
   * is the idiomatic example; the full vanilla reference stays one fetch away.
   * `<AgentSource>` (which has framework-native `react`/`vue`/`angular` overrides)
   * is unaffected. NOT passed by the per-page `.md` endpoint, so single-page
   * fetches still inline every demo.
   */
  omitDemoComponents?: boolean;
  /**
   * Absolute `.md` URL of the page being transformed, used as the link target in
   * the pointer emitted when `omitDemoComponents` is set. When omitted, the
   * pointer falls back to a generic "see the page's `.md` companion" note.
   */
  demoPageUrl?: string;
}

// #endregion

// #region Frontmatter

interface Frontmatter {
  title?: string;
  description?: string;
  /**
   * When explicitly `false`, the page is omitted from the inlined `llms-full.txt`
   * corpus (it stays linked in the `llms.txt` index). Used to keep sales/marketing
   * pages — e.g. release-history changelogs — out of the one-shot ingestion file
   * while leaving them discoverable. Defaults to included.
   */
  llmsFull?: boolean;
}

/** Split leading `---` frontmatter from the body. Minimal, no YAML dependency. */
function splitFrontmatter(raw: string): { data: Frontmatter; body: string } {
  const match = raw.match(/^---\r?\n([\s\S]*?)\r?\n---\r?\n?/);
  if (!match) return { data: {}, body: raw };
  const data: Frontmatter = {};
  for (const line of match[1].split(/\r?\n/)) {
    const kv = line.match(/^(\w+):\s*(.*)$/);
    if (!kv) continue;
    const key = kv[1];
    let value = kv[2].trim();
    // Strip surrounding quotes if present.
    if ((value.startsWith('"') && value.endsWith('"')) || (value.startsWith("'") && value.endsWith("'"))) {
      value = value.slice(1, -1);
    }
    if (key === 'title' || key === 'description') data[key] = value;
    else if (key === 'llmsFull') data.llmsFull = value !== 'false';
  }
  return { data, body: raw.slice(match[0].length) };
}

/**
 * Extract the `title` / `description` / `llmsFull` frontmatter from a raw MDX
 * page. Used by `llms.txt.ts` to label each index link, and by `llms-full.txt.ts`
 * to decide whether to inline a page, without running the full body transform.
 */
export function extractFrontmatter(raw: string): { title?: string; description?: string; llmsFull?: boolean } {
  return splitFrontmatter(raw).data;
}

// #endregion

// #region Audience regions

/**
 * Resolve `<Audience only="human|agent">…</Audience>` regions for the agent
 * corpus. Runs on the WHOLE body BEFORE the fenced-code split so a region whose
 * children include a ```code``` fence is handled as one unit (the open/close
 * tags would otherwise land in different fence segments).
 *
 * - `only="human"` regions (sales/marketing copy, motivational asides) are
 *   removed entirely — they render on the HTML site but must not pollute the
 *   implementation guidance an agent ingests.
 * - `only="agent"` regions (steering directives, extra gotchas, recipes) have
 *   only their wrapper tags removed; the inner Markdown is KEPT and flows through
 *   the rest of the transform. They render as nothing on the HTML site (see
 *   `Audience.astro`).
 *
 * Nesting is not supported (the non-greedy match stops at the first
 * `</Audience>`); do not nest `<Audience>` blocks.
 */
export function resolveAudienceRegions(body: string): string {
  return body
    .replace(/<Audience\b[^>]*\bonly=["']human["'][^>]*>[\s\S]*?<\/Audience\s*>/g, '')
    .replace(/<Audience\b[^>]*\bonly=["']agent["'][^>]*>([\s\S]*?)<\/Audience\s*>/g, '$1');
}

// #endregion

// #region Demo inlining

/** Extract the first `<script>` block's inner content from a demo `.astro` file. */
function extractDemoScript(astroSource: string): string | undefined {
  // Allow whitespace/attributes before the closing `>` (e.g. `</script >`) so the
  // pattern matches the same forgiving end tags a browser parser accepts
  // (CodeQL js/bad-tag-filter).
  const match = astroSource.match(/<script[^>]*>([\s\S]*?)<\/script\s*>/i);
  if (!match) return undefined;
  return match[1].replace(/^\r?\n/, '').replace(/\s+$/, '');
}

/** Build a fenced code block from a demo's script, or a comment if unavailable. */
function demoCodeBlock(relPath: string, resolveDemo: (p: string) => string | undefined): string {
  const source = resolveDemo(relPath);
  if (!source) return `<!-- demo source not found: ${relPath} -->`;
  const script = extractDemoScript(source);
  if (!script) return `<!-- demo has no <script> block: ${relPath} -->`;
  // Prefix the block with the demo's filename so an agent reading the inlined
  // code knows which `.astro` demo source it represents (provenance hint).
  const fileName = relPath.split(/[\\/]/).pop() ?? relPath;
  return '```ts\n// ' + fileName + '\n' + script + '\n```';
}

/**
 * One-line pointer that REPLACES an inlined demo when `omitDemoComponents` is set
 * (the per-framework corpus variants). The demo `.astro` sources are vanilla-only,
 * so a framework-scoped corpus links to the full reference instead of inlining
 * non-idiomatic code. Links to the page's `.md` companion when known.
 */
function demoPointer(relPath: string, pageUrl?: string): string {
  const fileName = relPath.split(/[\\/]/).pop() ?? relPath;
  return pageUrl
    ? `> Runnable demo \`${fileName}\` (vanilla reference) omitted from this framework-scoped corpus — see the [full example](${pageUrl}); the framework-native snippet above is the idiomatic version.`
    : `> Runnable demo \`${fileName}\` (vanilla reference) omitted — see the page's \`.md\` companion for the full example.`;
}

/**
 * Expand an `<AgentSource paths="a, b, c" />` directive into one fenced code
 * block per referenced demo-app module, each prefixed with a `// <repo path>`
 * provenance comment. Paths are comma-separated and repo-relative; the language
 * is inferred from the extension (`.css` → css, `.vue` → vue, `.tsx` → tsx,
 * `.html` → html, else ts). A path that cannot be resolved emits an HTML comment
 * instead of failing the build. Returns an empty string when no resolver is
 * supplied (tags are simply dropped).
 */
function agentSourceBlock(pathsAttr: string, resolveSource?: (p: string) => string | undefined): string {
  if (!resolveSource) return '';
  const blocks = pathsAttr
    .split(',')
    .map((p) => p.trim())
    .filter(Boolean)
    .map((p) => {
      const source = resolveSource(p);
      if (!source) return `<!-- agent source not found: ${p} -->`;
      const lang = langOfPath(p);
      return '```' + lang + '\n// ' + p + '\n' + source.replace(/\s+$/, '') + '\n```';
    });
  return '\n' + blocks.join('\n\n') + '\n';
}

/** Infer the fenced-code language tag for a demo-source path. */
function langOfPath(p: string): string {
  if (/\.css$/.test(p)) return 'css';
  if (/\.vue$/.test(p)) return 'vue';
  if (/\.tsx$/.test(p)) return 'tsx';
  if (/\.html$/.test(p)) return 'html';
  return 'ts';
}

/**
 * Pick the path list for an `<AgentSource>` tag, honouring per-framework
 * overrides. The default `paths` attribute is the vanilla / cross-framework set;
 * optional `react`/`vue`/`angular` attributes supply a framework-native set that
 * REPLACES it when the corpus is scoped to that framework. `vanilla` has no
 * dedicated attribute — `paths` already is the vanilla list. Returns `undefined`
 * when the tag has no usable path list.
 */
function selectAgentSourcePaths(tag: string, framework?: Framework): string | undefined {
  const attr = (name: string): string | undefined => {
    const m = tag.match(new RegExp(`\\b${name}=["']([^"']+)["']`));
    return m ? m[1] : undefined;
  };
  const override = framework && framework !== 'vanilla' ? attr(framework) : undefined;
  return override ?? attr('paths');
}

// #endregion

// #region Link rewriting

/**
 * Rewrite an internal docs link from its HTML (trailing-slash) form to the `.md`
 * companion, preserving any `#anchor` / `?query` suffix — but only when the
 * target actually has a generated `.md` page (per `hasDoc`). External links,
 * anchors, and unknown paths are returned unchanged.
 */
function rewriteDocLink(url: string, hasDoc?: (slug: string) => boolean): string {
  if (!hasDoc || !url.startsWith('/')) return url; // external, relative, or no predicate
  const suffixStart = url.search(/[#?]/);
  const path = suffixStart === -1 ? url : url.slice(0, suffixStart);
  const suffix = suffixStart === -1 ? '' : url.slice(suffixStart);
  // Slug is the lowercase path without leading/trailing slashes (matches keyToSlug).
  const slug = path.replace(/^\/+/, '').replace(/\/+$/, '').toLowerCase();
  if (!slug || !hasDoc(slug)) return url;
  return '/' + slug + '.md' + suffix;
}

// #endregion

// #region Framework tab filtering

/**
 * Map a `<TabItem>` label to the framework it represents, or `null` when the
 * label is framework-neutral (e.g. `npm`, `CDN`, `With a bundler`). Adapter
 * frameworks are matched first so a compound label like `React (TypeScript)`
 * classifies as `react`, not `vanilla`.
 */
function frameworkOfLabel(label: string): Framework | null {
  if (/react/i.test(label)) return 'react';
  if (/vue/i.test(label)) return 'vue';
  if (/angular/i.test(label)) return 'angular';
  if (/typescript|javascript|vanilla|html|^\s*ts\s*$|^\s*js\s*$/i.test(label)) return 'vanilla';
  return null;
}

/**
 * Within each `<Tabs>` block that offers framework alternatives (a React, Vue,
 * or Angular tab is present), keep only the `<TabItem>` for the target framework
 * and drop the rest. Framework-neutral tab groups (install managers, bundler vs
 * CDN, …) and blocks with no adapter-framework tab are left untouched. When the
 * group has no tab for the target framework, fall back to the vanilla/TypeScript
 * tab, and if even that is absent keep the whole group rather than emptying it.
 *
 * Runs on the full body BEFORE the fenced-code split (a `<TabItem>` wraps code
 * fences), so it must operate on `<Tabs>`/`<TabItem>` structure while intact —
 * i.e. before step 2b flattens them into `####` headings.
 */
export function filterFrameworkTabs(body: string, framework: Framework): string {
  return body.replace(/<Tabs\b[^>]*>([\s\S]*?)<\/Tabs>/g, (full: string, inner: string) => {
    const items: { raw: string; label: string }[] = [];
    const itemRe = /<TabItem\b[^>]*\blabel=["']([^"']+)["'][^>]*>[\s\S]*?<\/TabItem>/g;
    for (let m = itemRe.exec(inner); m; m = itemRe.exec(inner)) {
      items.push({ raw: m[0], label: m[1] });
    }
    if (items.length === 0) return full;
    const isFrameworkGroup = items.some((it) => {
      const f = frameworkOfLabel(it.label);
      return f === 'react' || f === 'vue' || f === 'angular';
    });
    if (!isFrameworkGroup) return full;

    let kept = items.filter((it) => frameworkOfLabel(it.label) === framework);
    if (kept.length === 0) kept = items.filter((it) => frameworkOfLabel(it.label) === 'vanilla');
    if (kept.length === 0) return full;
    return '<Tabs>\n' + kept.map((it) => it.raw).join('\n') + '\n</Tabs>';
  });
}

// #endregion

// #region Section dropping

/**
 * Remove whole H2 sections whose heading text matches `names` (case-insensitive,
 * after unwrapping any `[text](url)` link in the heading). A section spans from
 * its `## Heading` line through every following line up to — but not including —
 * the next `##` or `#` heading (so nested `###` subsections are dropped too).
 * Only level-2 headings are eligible; deeper or shallower headings never match.
 * Exported for unit testing.
 */
export function dropMarkdownSections(md: string, names: string[]): string {
  if (names.length === 0) return md;
  const drop = new Set(names.map((n) => n.trim().toLowerCase()));
  // Split on CRLF *or* LF: the source MDX is often CRLF-authored (Windows /
  // git autocrlf), and a trailing `\r` left on each line would defeat the
  // heading regex below (`.` never matches `\r`, and a non-multiline `$` won't
  // anchor before it). Re-joining with `\n` also normalises the output.
  const lines = md.split(/\r?\n/);
  const out: string[] = [];
  let dropping = false;
  for (const line of lines) {
    const heading = line.match(/^(#{1,6})\s+(.*)$/);
    if (heading) {
      const level = heading[1].length;
      if (level <= 2) {
        // A new `#`/`##` heading always ends any active drop. Decide afresh
        // whether THIS heading starts a new dropped section.
        const text = heading[2]
          .replace(/\[([^\]]*)\]\([^)]*\)/g, '$1')
          .replace(/[#*`]/g, '')
          .trim()
          .toLowerCase();
        dropping = level === 2 && drop.has(text);
        if (dropping) continue;
      }
    }
    if (!dropping) out.push(line);
  }
  return out.join('\n');
}

/**
 * Inverse of {@link dropMarkdownSections}: keep ONLY the preamble (every line
 * before the first `## ` heading) plus the H2 sections whose heading text matches
 * `names` (case-insensitive, after unwrapping any `[text](url)` link). Every other
 * level-2 section — and its nested `###` content — is removed. Only level-2
 * headings act as section boundaries. Exported for unit testing.
 */
export function keepMarkdownSections(md: string, names: string[]): string {
  if (names.length === 0) return md;
  const keep = new Set(names.map((n) => n.trim().toLowerCase()));
  // CRLF-safe split (see dropMarkdownSections): the source MDX is often
  // CRLF-authored, and a trailing `\r` would defeat the heading regex.
  const lines = md.split(/\r?\n/);
  const out: string[] = [];
  let keeping = true; // preamble before the first H2 is always kept
  for (const line of lines) {
    const heading = line.match(/^(#{1,6})\s+(.*)$/);
    if (heading && heading[1].length === 2) {
      const text = heading[2]
        .replace(/\[([^\]]*)\]\([^)]*\)/g, '$1')
        .replace(/[#*`]/g, '')
        .trim()
        .toLowerCase();
      keeping = keep.has(text);
    }
    if (keeping) out.push(line);
  }
  return out.join('\n');
}

// #endregion

// #region Transform

/**
 * Convert raw MDX source into agent-friendly Markdown.
 *
 * - Strips ESM `import` lines and MDX expression comments.
 * - Inlines `<ShowSource file="…">` and bare demo components as ```ts blocks.
 * - Flattens Starlight `<Tabs>` / `<TabItem label="…">` into `####` headings.
 * - Converts `<LinkCard>` → Markdown link bullets, `<Card title>` → `###`
 *   headings, `<Aside>` → `:::type` directives, `<Badge>` → inline text, and
 *   strips structural wrappers (`<CardGrid>`, `<Steps>`, `<FileTree>`, `<Icon>`).
 * - Leaves remaining directive syntax (`:::tip`) in place — agents tolerate it
 *   and it carries structure; aggressive flattening is deferred.
 */
export function mdxToAgentMarkdown(raw: string, opts: AgentMarkdownOptions): string {
  const { data, body: rawBody } = splitFrontmatter(raw);

  // Resolve `<Audience>` regions first (drop human-only, unwrap agent-only) so the
  // rest of the transform never sees the wrapper tags. Done before the fenced-code
  // split below because a region may straddle a ```code``` fence.
  const audienceResolved = resolveAudienceRegions(rawBody);

  // Optionally scope to a single framework: keep only the matching tab in each
  // framework tab group. Runs before the fenced split for the same straddling
  // reason, while `<Tabs>`/`<TabItem>` structure is still intact.
  const body = opts.frameworkFilter ? filterFrameworkTabs(audienceResolved, opts.frameworkFilter) : audienceResolved;

  // Split into fenced-code vs prose segments. ALL stripping/replacement runs on
  // prose only — example `import` lines inside ```code``` fences are real,
  // copy-ready guidance for the agent and MUST be preserved verbatim.
  const segments = body.split(/(```[\s\S]*?```)/g);
  const isFence = (s: string) => s.startsWith('```');

  // 1. Map imported demo component names → their `.astro` path (prose only).
  //    Only `demos/` imports are inlineable as runnable code. Other `.astro`
  //    imports are interactive doc widgets (e.g. `<ThemeBuilder/>`,
  //    `<CSSVariableReference/>`, `<ShowSource/>`) whose rendered output is
  //    generated at runtime and has NO inlineable source — track their names
  //    separately so step 4b can strip the leftover tags cleanly instead of
  //    emitting a bogus "demo source not found" comment.
  const componentToDemo = new Map<string, string>();
  const nonDemoComponents = new Set<string>();
  const importRe = /^import\s+(\w+)\s+from\s+['"]([^'"]+\.astro)['"];?\s*$/gm;
  for (const seg of segments) {
    if (isFence(seg)) continue;
    for (let m = importRe.exec(seg); m; m = importRe.exec(seg)) {
      const [, name, path] = m;
      if (/(^|\/)demos\//.test(path)) componentToDemo.set(name, path);
      else nonDemoComponents.add(name);
    }
  }

  const transformed = segments.map((seg) => {
    if (isFence(seg)) return seg; // leave code blocks untouched

    let out = seg;
    // 1b. Restore agent-only headings. Inside `<Audience only="agent">` blocks,
    //     section breaks are authored as `_## Heading` (underscore-prefixed) so
    //     Starlight's compile-time table-of-contents harvest — which scans real
    //     ATX headings even inside conditionally-rendered slots — skips them and
    //     the human page gets no phantom TOC links. `_#…` is not a valid heading
    //     in CommonMark, so it never reaches the human site. Here we drop the
    //     leading `_` to turn it back into a true Markdown heading the agent can
    //     navigate by. Runs in prose only, so `_#` inside a code fence is kept.
    out = out.replace(/^_(#{1,6} )/gm, '$1');
    // 2. Drop ESM import lines and MDX comments.
    out = out.replace(/^import\s+.*$/gm, '');
    out = out.replace(/\{\/\*[\s\S]*?\*\/\}/g, '');

    // 2b. Flatten Starlight `<Tabs>` / `<TabItem label="…">` into `####` headings.
    //     Tabs render as interactive widgets in HTML but add noise in plain
    //     Markdown; the tab label is the only meaningful structure, so promote it
    //     to a heading and drop the wrapper tags.
    out = out.replace(/<TabItem\b[^>]*\blabel=["']([^"']+)["'][^>]*>/g, (_full, label: string) => `\n#### ${label}\n`);
    out = out.replace(/<\/TabItem>/g, '');
    out = out.replace(/<Tabs\b[^>]*>/g, '');
    out = out.replace(/<\/Tabs>/g, '');

    // 2c. Flatten remaining Starlight components into plain Markdown. These are
    //     raw JSX in the source MDX; left untouched they leak as literal tags an
    //     agent can't use. All replacements operate on OPEN and CLOSE tags
    //     independently (never as `<X>…</X>` pairs) so they survive the
    //     fenced-code segment split above — a component whose children include a
    //     ```code``` block has its open/close tags in DIFFERENT segments.
    //   - `<LinkCard title description href />` → a Markdown link bullet (the
    //     `href` is rewritten to its `.md` companion by step 5 below).
    out = out.replace(/<LinkCard\b([^>]*?)\/?>/g, (_full, attrs: string) => {
      const title = attrs.match(/\btitle=["']([^"']*)["']/)?.[1] ?? '';
      const href = attrs.match(/\bhref=["']([^"']*)["']/)?.[1] ?? '';
      const description = attrs.match(/\bdescription=["']([^"']*)["']/)?.[1];
      if (!href) return '';
      return `- [${title || href}](${href})${description ? `: ${description}` : ''}`;
    });
    //   - `<Card title="…">` → an `###` heading; bare `<Card>` / `</Card>` drop.
    out = out.replace(/<Card\b([^>]*)>/g, (_full, attrs: string) => {
      const title = attrs.match(/\btitle=["']([^"']*)["']/)?.[1];
      return title ? `\n### ${title}\n` : '';
    });
    out = out.replace(/<\/Card>/g, '');
    //   - `<Aside type="…" [title="…"]>` → the equivalent `:::type[title]`
    //     directive already used throughout the prose; `</Aside>` → closing `:::`.
    out = out.replace(/<Aside\b([^>]*)>/g, (_full, attrs: string) => {
      const type = attrs.match(/\btype=["']([^"']*)["']/)?.[1] ?? 'note';
      const title = attrs.match(/\btitle=["']([^"']*)["']/)?.[1];
      return `:::${type}${title ? `[${title}]` : ''}`;
    });
    out = out.replace(/<\/Aside>/g, ':::');
    //   - `<Badge text="…" />` → its inline text in parens; structural wrappers
    //     (`<CardGrid>`, `<Steps>`, `<FileTree>`) and `<Icon />` carry no textual
    //     value, so strip the tags and keep any inner Markdown.
    out = out.replace(/<Badge\b[^>]*\btext=["']([^"']*)["'][^>]*\/?>/g, (_full, text: string) => `(${text})`);
    out = out.replace(/<Icon\b[^>]*\/?>/g, '');
    out = out.replace(/<\/?(?:CardGrid|Steps|FileTree)\b[^>]*>/g, '');

    // 3. Inline `<ShowSource file="…"> … </ShowSource>` blocks first (the `file`
    //    attribute points directly at the demo, and its children are the same
    //    demo component, so replacing the whole block avoids duplicate code).
    //    When `omitDemoComponents` is set (framework-scoped corpus), emit a
    //    pointer to the page's `.md` companion instead of the vanilla source.
    out = out.replace(
      /<ShowSource\b[^>]*\bfile=["']([^"']+)["'][^>]*>[\s\S]*?<\/ShowSource>/g,
      (_full, file: string) =>
        '\n' +
        (opts.omitDemoComponents ? demoPointer(file, opts.demoPageUrl) : demoCodeBlock(file, opts.resolveDemo)) +
        '\n',
    );

    // 3b. Expand `<AgentSource paths="…" />` directives — an agent-only mechanism
    //     (placed inside `<Audience only="agent">`) that inlines real demo-app
    //     modules from repo-root `demos/` as fenced code, so the corpus carries a
    //     full end-to-end reference implementation from the live demo's own
    //     source. In a framework-scoped corpus, a per-framework attribute
    //     (`react`/`vue`/`angular`) swaps in that framework's native demo set;
    //     otherwise the default `paths` (vanilla) set is used. Self-closing, so
    //     handle before the non-demo-component strip in 4b (which would otherwise
    //     remove the tag and lose the inlined source).
    out = out.replace(/<AgentSource\b[^>]*\/?>/g, (tag: string) => {
      const paths = selectAgentSourcePaths(tag, opts.frameworkFilter);
      return paths ? agentSourceBlock(paths, opts.resolveSource) : '';
    });

    // 4. Inline remaining standalone demo components (`<IntroBasicDemo />` or
    //    `<IntroBasicDemo>…</IntroBasicDemo>`). When `omitDemoComponents` is set
    //    (framework-scoped corpus), emit a `.md` pointer instead of the vanilla
    //    source so the corpus stays free of non-idiomatic `HTMLElement` code.
    for (const [name, demoPath] of componentToDemo) {
      const selfClosing = new RegExp(`<${name}\\b[^>]*/>`, 'g');
      const paired = new RegExp(`<${name}\\b[^>]*>[\\s\\S]*?</${name}>`, 'g');
      const block =
        '\n' +
        (opts.omitDemoComponents
          ? demoPointer(demoPath, opts.demoPageUrl)
          : demoCodeBlock(demoPath, opts.resolveDemo)) +
        '\n';
      out = out.replace(paired, block).replace(selfClosing, block);
    }

    // 4b. Strip leftover tags for imported NON-demo components (interactive doc
    //     widgets like `<ThemeBuilder/>` / `<CSSVariableReference/>` whose output
    //     is generated at runtime, so there is nothing to inline). Without this
    //     they would either leak as raw JSX or — because they are `.astro`
    //     imports — be mis-treated as demos and emit a "demo source not found"
    //     comment. `<ShowSource>` is already consumed in step 3; any stray
    //     instance is dropped here too.
    for (const name of nonDemoComponents) {
      // Special-case: the theming guide's `<CSSVariableReference />` is replaced
      // with an injected Markdown table (variable name + description) rather than
      // stripped, so the CSS-variable reference survives into the agent corpus.
      if (name === 'CSSVariableReference' && opts.cssVarReference) {
        const selfClosing = new RegExp(`<${name}\\b[^>]*/>`, 'g');
        const paired = new RegExp(`<${name}\\b[^>]*>[\\s\\S]*?</${name}>`, 'g');
        out = out.replace(paired, opts.cssVarReference).replace(selfClosing, opts.cssVarReference);
        continue;
      }
      const selfClosing = new RegExp(`<${name}\\b[^>]*/>`, 'g');
      const paired = new RegExp(`<${name}\\b[^>]*>[\\s\\S]*?</${name}>`, 'g');
      out = out.replace(paired, '').replace(selfClosing, '');
    }

    // 5. Rewrite internal doc links from their HTML form to the `.md` companion
    //    so agents keep navigating the markdown graph. Match only the `](url)`
    //    tail (not the link text) so labels containing brackets — e.g.
    //    `[`ColumnConfig[]`](…)` — still rewrite. `hasDoc` gates out images and
    //    any non-doc path, so matching bare `](…)` is safe.
    out = out.replace(/\]\((\/[^)\s]+)\)/g, (full, url: string) => {
      const rewritten = rewriteDocLink(url, opts.hasDoc);
      return rewritten === url ? full : `](${rewritten})`;
    });
    return out;
  });

  // 6. Rejoin and collapse the blank lines left behind by stripped content.
  //    Normalise whitespace-only lines first (stripped wrapper tags were often
  //    indented, leaving lines of stray spaces) so the blank-line collapse works.
  let out = transformed
    .join('')
    .replace(/^[ \t]+$/gm, '')
    .replace(/\n{3,}/g, '\n\n')
    .trim();

  // 6b. Drop illustrative/navigational H2 sections requested by the corpus
  //     builder (e.g. `## Demos`, `## See Also`). Runs after the body is fully
  //     transformed so it sees real `##` headings, and collapses the blank lines
  //     the removal leaves behind. Skipped entirely when no sections are listed.
  if (opts.dropSections?.length) {
    out = dropMarkdownSections(out, opts.dropSections)
      .replace(/\n{3,}/g, '\n\n')
      .trim();
  }

  // 6c. Inverse filter: keep only the preamble + listed H2 sections (e.g. demote
  //     plugin pages to intro + Installation + Basic Usage). Runs after 6b so it
  //     sees real `##` headings; collapses the blank lines the removal leaves.
  if (opts.keepSections?.length) {
    out = keepMarkdownSections(out, opts.keepSections)
      .replace(/\n{3,}/g, '\n\n')
      .trim();
  }

  // 7. Prepend a title heading + description so the page is self-describing.
  const header: string[] = [];
  if (data.title) header.push(`# ${data.title}`);
  if (data.description) header.push(`> ${data.description}`);
  return (header.length ? header.join('\n\n') + '\n\n' : '') + out + '\n';
}

// #endregion
