/// <reference types="vite/client" />
/**
 * _llm-sources.ts — Shared build-time source maps + slug helpers for the agent
 * markdown endpoints (`[...slug].md.ts`, `llms.txt.ts`, `llms-full.txt.ts`).
 *
 * Underscore prefix keeps this OUT of the route table. Centralising the
 * `import.meta.glob` of doc + demo sources here gives all three endpoints one
 * source of truth and one slug-derivation rule, so they can never disagree
 * about which pages exist or where they live.
 */

// Raw source of every grid doc page (build-time, via Vite). Paths are relative
// to THIS file (`src/pages/`), so `../` reaches `src/`.
export const docSources = import.meta.glob<string>('../content/docs/grid/**/*.{md,mdx}', {
  query: '?raw',
  import: 'default',
  eager: true,
});

// Raw source of every demo component, for inlining their `<script>` blocks.
export const demoSources = import.meta.glob<string>('../components/demos/**/*.astro', {
  query: '?raw',
  import: 'default',
  eager: true,
});

/** Convert a glob key to a clean docs slug: `.../grid/introduction.mdx` → `grid/introduction`. */
export function keyToSlug(key: string): string {
  const slug = key
    .replace(/^.*?\/content\/docs\//, '')
    .replace(/\.(md|mdx)$/, '')
    .replace(/\/index$/, '');
  // Starlight lowercases route slugs (e.g. autogenerated TypeDoc pages live at
  // `Classes/DataGridElement.mdx` but serve at `/classes/datagridelement/`), so
  // lowercase here too to keep `.md` URLs aligned with their HTML counterparts.
  // Safe: TypeDoc/curated paths are ASCII identifiers, so case is the only diff.
  return slug.toLowerCase();
}

/** Resolve a demo path (`demos/Foo.astro`) to its raw source from the glob map. */
export function resolveDemo(relPath: string): string | undefined {
  const needle = relPath.replace(/^.*?demos\//, 'demos/');
  for (const [key, source] of Object.entries(demoSources)) {
    if (key.endsWith('/' + needle) || key.endsWith(needle)) return source;
  }
  return undefined;
}

/** Set of all generated doc slugs, used to rewrite internal links to their `.md` form. */
export const knownSlugs = new Set(Object.keys(docSources).map(keyToSlug));

/** Return `true` if the given lowercase doc slug has a generated `.md` companion page. */
export const hasDoc = (slug: string): boolean => knownSlugs.has(slug);

/**
 * Classify a doc slug into a top-level documentation section. Drives ordering
 * and grouping in `llms.txt` (the index) and `llms-full.txt` (the full dump).
 * Per-symbol TypeDoc API pages are reported as `'API'` — these live either under
 * an `/api/` path OR under a reflection-kind directory (`classes/`,
 * `interfaces/`, `functions/`, `types/`, `variables/`, `enumerations/`) nested
 * beneath a plugin/adapter page (e.g. `grid/plugins/clipboard/classes/...`).
 */
export function sectionOf(slug: string): string {
  if (/(^|\/)api\//.test(slug)) return 'API';
  if (/\/(classes|interfaces|functions|types|variables|enumerations)\//.test(slug)) return 'API';
  if (slug.startsWith('grid/guides/')) return 'Guides';
  if (slug.startsWith('grid/plugins/')) return 'Plugins';
  if (slug.startsWith('grid/plugin-development')) return 'Plugin Development';
  if (slug.startsWith('grid/framework-adapters')) return 'Framework Adapters';
  if (slug.startsWith('grid/angular/')) return 'Angular';
  if (slug.startsWith('grid/react/')) return 'React';
  if (slug.startsWith('grid/vue/')) return 'Vue';
  return 'Core Documentation';
}

/** Section display order for both generated files. */
export const SECTION_ORDER = [
  'Core Documentation',
  'Guides',
  'Plugins',
  'Plugin Development',
  'Framework Adapters',
  'Angular',
  'React',
  'Vue',
  'API',
] as const;

/**
 * Sub-group an API page slug into a human area heading for the linked
 * `## API Reference` sections in `llms.txt` and `llms-full.txt`. Per-symbol
 * TypeDoc pages live under several roots (curated `/api/*` trees, per-plugin
 * reflection folders, and adapter `/api/*` trees).
 */
export function apiAreaOf(slug: string): string {
  if (slug.startsWith('grid/api/core')) return 'Core';
  if (slug.startsWith('grid/api/plugin-development')) return 'Plugin Development';
  if (slug.startsWith('grid/api/framework-adapters')) return 'Framework Adapters';
  if (slug.startsWith('grid/angular/api')) return 'Angular Adapter';
  if (slug.startsWith('grid/react/api')) return 'React Adapter';
  if (slug.startsWith('grid/vue/api')) return 'Vue Adapter';
  if (slug.startsWith('grid/plugins/')) return 'Plugins';
  return 'Other';
}

/** Display order for the API-area subsections. */
export const API_AREA_ORDER = [
  'Core',
  'Plugins',
  'Plugin Development',
  'Framework Adapters',
  'Angular Adapter',
  'React Adapter',
  'Vue Adapter',
  'Other',
] as const;
