/// <reference types="vite/client" />
/**
 * _llm-sources.ts — Shared build-time source maps + slug helpers for the agent
 * markdown endpoints (`[...slug].md.ts`, `llms.txt.ts`, `llms-full.txt.ts`).
 *
 * Underscore prefix keeps this OUT of the route table. Centralising the
 * `import.meta.glob` of doc + demo sources here gives all three endpoints one
 * source of truth and one slug-derivation rule, so they can never disagree
 * about which pages exist or where they live.
 */
import { CSS_VARIABLES } from '../data/css-variable-registry.js';
import type { Framework } from './_llm-markdown.js';

// Raw source of every grid doc page (build-time, via Vite). Paths are relative
// to THIS file (`src/pages/`), so `../` reaches `src/`.
export const docSources = import.meta.glob<string>('../content/docs/grid/**/*.{md,mdx}', {
  query: '?raw',
  import: 'default',
  eager: true,
});

// Raw source of every demo component, for inlining their `<script>` blocks.
export const demoSources = import.meta.glob<string>('../components/demos/**/*.astro', {
  query: '?raw',
  import: 'default',
  eager: true,
});

// Raw source of the real demo-app TypeScript modules (repo-root `demos/`), for
// inlining a full end-to-end reference implementation into the agent corpus via
// the `<AgentSource paths="…" />` directive. Unlike the docs `demoSources` above
// (whose `<script>` only calls an opaque factory through the `@demo/*` alias),
// these are the canonical advanced grid-config files the live demo actually runs
// — so the corpus teaches from the single source of truth with zero drift. The
// vanilla demo + shared models are the cross-framework default; the React, Vue,
// and Angular demo trees back the per-framework `<AgentSource>` overrides used by
// the framework-scoped `llms-full-{framework}.txt` corpora. Paths escape the docs
// root (`../../../../`) to reach repo-root `demos/`, which Vite already reads via
// the `@demo/*` aliases.
export const demoAppSources = import.meta.glob<string>(
  [
    '../../../../demos/vanilla/src/demos/**/*.ts',
    '../../../../demos/shared/**/*.ts',
    '../../../../demos/react/src/demos/**/*.{ts,tsx}',
    '../../../../demos/vue/src/demos/**/*.{ts,vue}',
    '../../../../demos/angular/src/demos/**/*.{ts,html}',
  ],
  { query: '?raw', import: 'default', eager: true },
);

/** Convert a glob key to a clean docs slug: `.../grid/introduction.mdx` → `grid/introduction`. */
export function keyToSlug(key: string): string {
  const slug = key
    .replace(/^.*?\/content\/docs\//, '')
    .replace(/\.(md|mdx)$/, '')
    .replace(/\/index$/, '');
  // Starlight lowercases route slugs (e.g. autogenerated TypeDoc pages live at
  // `Classes/DataGridElement.mdx` but serve at `/classes/datagridelement/`), so
  // lowercase here too to keep `.md` URLs aligned with their HTML counterparts.
  // Safe: TypeDoc/curated paths are ASCII identifiers, so case is the only diff.
  return slug.toLowerCase();
}

/** Resolve a demo path (`demos/Foo.astro`) to its raw source from the glob map. */
export function resolveDemo(relPath: string): string | undefined {
  const needle = relPath.replace(/^.*?demos\//, 'demos/');
  for (const [key, source] of Object.entries(demoSources)) {
    if (key.endsWith('/' + needle) || key.endsWith(needle)) return source;
  }
  return undefined;
}

/**
 * Resolve a repo-relative demo-app source path (e.g.
 * `demos/vanilla/src/demos/employee-management/grid-config.ts`) to its raw text
 * from the `demoAppSources` glob, by matching the glob key's suffix. Used by the
 * `<AgentSource paths="…" />` directive to inline real demo modules into the
 * agent corpus. Returns `undefined` if no module matches.
 */
export function resolveDemoSource(relPath: string): string | undefined {
  const needle = relPath.replace(/^\/+/, '');
  for (const [key, source] of Object.entries(demoAppSources)) {
    if (key.endsWith('/' + needle) || key.endsWith(needle)) return source;
  }
  return undefined;
}

/** Set of all generated doc slugs, used to rewrite internal links to their `.md` form. */
export const knownSlugs = new Set(Object.keys(docSources).map(keyToSlug));

/** Return `true` if the given lowercase doc slug has a generated `.md` companion page. */
export const hasDoc = (slug: string): boolean => knownSlugs.has(slug);

/**
 * Classify a doc slug into a top-level documentation section. Drives ordering
 * and grouping in `llms.txt` (the index) and `llms-full.txt` (the full dump).
 * Per-symbol TypeDoc API pages are reported as `'API'` — these live either under
 * an `/api/` path OR under a reflection-kind directory (`classes/`,
 * `interfaces/`, `functions/`, `types/`, `variables/`, `enumerations/`) nested
 * beneath a plugin/adapter page (e.g. `grid/plugins/clipboard/classes/...`).
 */
export function sectionOf(slug: string): string {
  if (/(^|\/)api\//.test(slug)) return 'API';
  if (/\/(classes|interfaces|functions|types|variables|enumerations)\//.test(slug)) return 'API';
  if (slug.startsWith('grid/guides/')) return 'Guides';
  if (slug.startsWith('grid/plugins/')) return 'Plugins';
  if (slug.startsWith('grid/plugin-development')) return 'Plugin Development';
  if (slug.startsWith('grid/framework-adapters')) return 'Framework Adapters';
  if (slug.startsWith('grid/angular/')) return 'Angular';
  if (slug.startsWith('grid/react/')) return 'React';
  if (slug.startsWith('grid/vue/')) return 'Vue';
  return 'Core Documentation';
}

/** Section display order for both generated files. */
export const SECTION_ORDER = [
  'Core Documentation',
  'Guides',
  'Plugins',
  'Plugin Development',
  'Framework Adapters',
  'Angular',
  'React',
  'Vue',
  'API',
] as const;

/**
 * Sub-group an API page slug into a human area heading for the linked
 * `## API Reference` sections in `llms.txt` and `llms-full.txt`. Per-symbol
 * TypeDoc pages live under several roots (curated `/api/*` trees, per-plugin
 * reflection folders, and adapter `/api/*` trees).
 */
export function apiAreaOf(slug: string): string {
  if (slug.startsWith('grid/api/core')) return 'Core';
  if (slug.startsWith('grid/api/plugin-development')) return 'Plugin Development';
  if (slug.startsWith('grid/api/framework-adapters')) return 'Framework Adapters';
  if (slug.startsWith('grid/angular/api')) return 'Angular Adapter';
  if (slug.startsWith('grid/react/api')) return 'React Adapter';
  if (slug.startsWith('grid/vue/api')) return 'Vue Adapter';
  if (slug.startsWith('grid/plugins/')) return 'Plugins';
  return 'Other';
}

/** Adapter slug prefixes that are foreign to each framework-scoped corpus. */
const FOREIGN_ADAPTER_PREFIXES: Record<Framework, readonly string[]> = {
  vanilla: ['grid/angular/', 'grid/react/', 'grid/vue/'],
  react: ['grid/angular/', 'grid/vue/'],
  vue: ['grid/angular/', 'grid/react/'],
  angular: ['grid/react/', 'grid/vue/'],
};

/**
 * Return `true` when a page belongs to a framework adapter OTHER than the target
 * framework, so it can be dropped from that framework's scoped corpus. Matches on
 * the slug prefix, covering both adapter prose pages (`grid/angular/**`) and their
 * per-symbol API pages (`grid/angular/api/**`). `null` (the "everything" variant)
 * never excludes anything.
 */
export function isForeignFrameworkPage(slug: string, framework: Framework | null): boolean {
  if (!framework) return false;
  return FOREIGN_ADAPTER_PREFIXES[framework].some((prefix) => slug.startsWith(prefix));
}

/** Display order for the API-area subsections. */
export const API_AREA_ORDER = [
  'Core',
  'Plugins',
  'Plugin Development',
  'Framework Adapters',
  'Angular Adapter',
  'React Adapter',
  'Vue Adapter',
  'Other',
] as const;

/**
 * Reading order for the conceptual "Core Documentation" pages — generic → specific
 * (orientation → setup → core concepts → demos → architecture → reference → history),
 * so both agent files lead with what-it-is and how-to-set-up before deep internals or
 * historical material. Pages not listed sort alphabetically AFTER these. Shared by
 * `llms.txt` (index) and `llms-full.txt` (corpus) so both present the same narrative arc.
 *
 * NOTE: `ai`, `demos`, `comparison`, and `changelog` stay listed here even though they are
 * EXCLUDED from the `llms-full.txt` corpus (via `llmsFull: false`). The exclusion only
 * affects the corpus; the `llms.txt` INDEX still links every page and uses this array to
 * order them. Dropping them here would push those pages to the alphabetical tail of the
 * index in an arbitrary order — they belong in the curated reading order regardless.
 */
export const CORE_ORDER = [
  'grid/introduction',
  'grid/getting-started',
  'grid/ai',
  'grid/core',
  'grid/demos',
  'grid/architecture',
  'grid/api-reference',
  'grid/errors',
  'grid/comparison',
  'grid/changelog',
] as const;

/**
 * Comparator for two slugs within the SAME section. "Core Documentation" follows the
 * curated `CORE_ORDER` reading order (generic → specific); every other section sorts
 * alphabetically by slug. Section-level ordering is `SECTION_ORDER` (Core → Guides →
 * Plugins → Plugin Development → Framework Adapters → Angular/React/Vue), itself
 * generic → specific. Used by both agent endpoints for one consistent order.
 */
export function compareSlugsInSection(section: string, a: string, b: string): number {
  if (section === 'Core Documentation') {
    const ai = CORE_ORDER.indexOf(a as (typeof CORE_ORDER)[number]);
    const bi = CORE_ORDER.indexOf(b as (typeof CORE_ORDER)[number]);
    const an = ai === -1 ? Infinity : ai;
    const bn = bi === -1 ? Infinity : bi;
    if (an !== bn) return an - bn;
  }
  return a.localeCompare(b);
}

/**
 * Markdown rendering of the live `<CSSVariableReference />` widget for the agent
 * corpus. The human page shows three columns (Variable / Current Value / Description);
 * for agents only the **variable name + description** carry meaning — the "current
 * value" column is a runtime-computed convenience, so it is dropped here. Grouped by
 * the same category headings the widget renders. Injected into `mdxToAgentMarkdown`
 * via `AgentMarkdownOptions.cssVarReference` so the transform stays free of doc-data
 * imports (it cannot import `CSS_VARIABLES` itself and remain pure).
 */
export const cssVariableReferenceMarkdown: string = Object.entries(CSS_VARIABLES)
  .map(([category, defs]) => {
    const rows = defs.map((def) => `| \`${def.name}\` | ${def.description} |`).join('\n');
    return `### ${category}\n\n| Variable | Description |\n| --- | --- |\n${rows}`;
  })
  .join('\n\n');
