// Shared types for the competitor benchmark framework.
// One adapter per third-party grid; Toolbox Grid is also implemented as an
// adapter so the orchestrator stays symmetric.

/**
 * "Macro" metrics: operations that do real, scaling work (touch every row
 * or rebuild large internal structures). The headline speedup is computed
 * as the geometric mean of these ratios only — mixing in noise-floor
 * micro-ops would dilute the comparison and exaggerate the win.
 */
export const MACRO_METRICS = ['Time to first paint', 'Sort', 'Filter', 'Data replacement'] as const;

/**
 * "Micro" metrics: per-interaction operations whose cost is bounded by one
 * frame on a virtualized grid. Reported separately and excluded from the
 * headline speedup because most numbers cluster around the ~16 ms vsync
 * floor regardless of grid quality. They still show up clearly when a
 * competitor regresses (e.g. AG Grid column resize at scale).
 */
export const MICRO_METRICS = ['Update single row', 'Column resize', 'Scroll to end', 'Grid destroy'] as const;

export const TIME_METRICS = [...MACRO_METRICS, ...MICRO_METRICS] as const;

/**
 * Count of DOM nodes attached to the grid host after initial render. Shown
 * once as a "viewport overhead" stat — not per-scale, because every
 * benchmarked grid is virtualized and the count is constant across row
 * counts. Replaces the old byte-based "Memory usage" metric, which used
 * `performance.memory.usedJSHeapSize` (browser-quantized, returned 0 B
 * for sub-megabyte allocations, indefensible cross-grid).
 */
export const DOM_METRIC = 'DOM nodes' as const;

/**
 * Derived metric: the sum of all macro times at one scale point. Gives a
 * single "end-to-end responsiveness" number that is hard to game with
 * individual fast paths. Computed in the renderer; adapters never set it.
 */
export const ROUND_TRIP_METRIC = 'Round-trip (sum of macro)' as const;

export const ALL_METRICS = [...TIME_METRICS, DOM_METRIC] as const;
export type MetricName = (typeof ALL_METRICS)[number] | typeof ROUND_TRIP_METRIC;

/** A single benchmark run at one row-count scale point. */
export interface ScaleResult {
  rowCount: number;
  /** Toolbox results for this scale point. Empty until the run completes. */
  tbw: Map<MetricName, number>;
  /** Competitor results for this scale point. Empty until the run completes. */
  competitor: Map<MetricName, number>;
}

/**
 * One row of benchmark data. Generated by `generateRows()` in shared.ts;
 * the shape is `{ id: number, col1: string, col2: string, ... }`.
 */
export type BenchmarkRow = Record<string, unknown> & { id: number };

/** Column descriptor consumed by every adapter. */
export interface BenchmarkColumn {
  field: string;
  header: string;
  width: number;
}

/**
 * A pluggable grid implementation under benchmark. Each adapter is a small
 * file that knows how to load the grid (usually from CDN), mount it, run
 * the standard sequence of operations, and return the metric map.
 */
export interface CompetitorAdapter {
  /** Stable id used as map key and in the dropdown value, e.g. `'ag-grid'`. */
  readonly id: string;
  /** Long display name, e.g. `'AG Grid Community'`. */
  readonly name: string;
  /** Short label rendered next to chart bars, e.g. `'AG'`. */
  readonly shortLabel: string;
  /** Brand colour used for the competitor's bars and config panel header. */
  readonly color: string;
  /** Optional one-liner shown under the dropdown after selection. */
  readonly description?: string;
  /** Documentation/source link for the competitor. */
  readonly url: string;
  /**
   * Source snippet shown in the "Grid Configurations" panel so visitors can
   * verify the comparison is fair.
   */
  readonly configCode: string;
  /**
   * Resolved version after `load()` completes. Empty string if unknown.
   * Mutable so the loader can fill it in.
   */
  version: string;
  /**
   * Optional cap on row count. The orchestrator will skip any scale point
   * larger than this and show no bars for the competitor at that scale,
   * avoiding browser hangs on non-virtualized grids (e.g. Grid.js).
   */
  readonly maxRowCount?: number;
  /** Load any CDN assets the adapter needs. Idempotent. */
  load(): Promise<void>;
  /**
   * Run the full benchmark sequence at one scale point. Implementations
   * mount their grid into `gridArea`, run each metric, and clean up.
   */
  runAtScale(gridArea: HTMLElement, rowCount: number): Promise<Map<MetricName, number>>;
}
