// Shared types for the competitor benchmark framework.
// One adapter per third-party grid; Toolbox Grid is also implemented as an
// adapter so the orchestrator stays symmetric.

export const TIME_METRICS = [
  'Initial render',
  'Scroll avg frame',
  'Sort',
  'Filter',
  'Data replacement',
  'Update single row',
  'Column resize',
  'Scroll to end',
  'Grid destroy',
] as const;
export const MEMORY_METRIC = 'Memory usage' as const;
export const ALL_METRICS = [...TIME_METRICS, MEMORY_METRIC] as const;
export type MetricName = (typeof ALL_METRICS)[number];

/** A single benchmark run at one row-count scale point. */
export interface ScaleResult {
  rowCount: number;
  /** Toolbox results for this scale point. Empty until the run completes. */
  tbw: Map<MetricName, number>;
  /** Competitor results for this scale point. Empty until the run completes. */
  competitor: Map<MetricName, number>;
}

/**
 * One row of benchmark data. Generated by `generateRows()` in shared.ts;
 * the shape is `{ id: number, col1: string, col2: string, ... }`.
 */
export type BenchmarkRow = Record<string, unknown> & { id: number };

/** Column descriptor consumed by every adapter. */
export interface BenchmarkColumn {
  field: string;
  header: string;
  width: number;
}

/**
 * A pluggable grid implementation under benchmark. Each adapter is a small
 * file that knows how to load the grid (usually from CDN), mount it, run
 * the standard sequence of operations, and return the metric map.
 */
export interface CompetitorAdapter {
  /** Stable id used as map key and in the dropdown value, e.g. `'ag-grid'`. */
  readonly id: string;
  /** Long display name, e.g. `'AG Grid Community'`. */
  readonly name: string;
  /** Short label rendered next to chart bars, e.g. `'AG'`. */
  readonly shortLabel: string;
  /** Brand colour used for the competitor's bars and config panel header. */
  readonly color: string;
  /** Optional one-liner shown under the dropdown after selection. */
  readonly description?: string;
  /** Documentation/source link for the competitor. */
  readonly url: string;
  /**
   * Source snippet shown in the "Grid Configurations" panel so visitors can
   * verify the comparison is fair.
   */
  readonly configCode: string;
  /**
   * Resolved version after `load()` completes. Empty string if unknown.
   * Mutable so the loader can fill it in.
   */
  version: string;
  /** Load any CDN assets the adapter needs. Idempotent. */
  load(): Promise<void>;
  /**
   * Run the full benchmark sequence at one scale point. Implementations
   * mount their grid into `gridArea`, run each metric, and clean up.
   */
  runAtScale(gridArea: HTMLElement, rowCount: number): Promise<Map<MetricName, number>>;
}
