/**
 * Cut the recorded promo scenes into a reel, from an editable edit list.
 *
 * A promo run produces several minutes of footage: every scene is a full CI
 * test, complete with navigation, narration and assertions. Nobody watches that.
 * What sells the grid is a montage of *money shots* — the sort flipping, rows
 * collapsing under a filter, the table morphing into cards.
 *
 * Two videos come out of the same footage:
 *
 *  - `promo-full.mp4` — every scene recording end to end, stream-copied.
 *  - `promo-reel.mp4` — the cut you control, assembled from `promo-cut.json`.
 *
 * **`promo-cut.json` is the edit.** It is a plain list of
 * `{scene, in, out}` entries: take that scene's recording from `in` to `out`
 * seconds, and play the entries in array order. Reorder it, retime it, drop
 * entries, or point two entries at different moments of the same recording —
 * the file is the whole editorial decision, and nothing in it is derived at
 * stitch time.
 *
 * It is generated on first run (or with `--init`) from the `clip()` marks the
 * scenes recorded, so the starting point is already a sane assembly: cards
 * first, features in declaration order, punch and outro last, each entry
 * spanning the full window its `clip()` measured and pre-`skip`ped when the
 * scene opted out with `reel: false`. After that the file wins — re-running
 * `--init` is how you throw your edit away and start over.
 *
 * Scenes are addressed by **test title**, not by directory: Playwright hashes
 * the output directory names, and the titles are what you see in the spec.
 *
 * Usage:
 *   bun run promo                  # record the scenes
 *   bun run promo:stitch           # → promo-output/promo-reel.mp4  (from promo-cut.json)
 *   bun run promo:full             # → promo-output/promo-full.mp4  (untrimmed)
 *   bun run promo:stitch --init    # regenerate promo-cut.json, discarding manual edits
 *   bun run promo:stitch --xfade=0 # hard cuts instead of dissolves
 */
import { spawnSync } from 'node:child_process';
import { existsSync, globSync, mkdirSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const outputDir = join(root, 'apps/docs-e2e/promo-output');
const reportPath = join(outputDir, 'report.json');
const workDir = join(outputDir, 'segments');
/**
 * The edit list. Checked in, next to the specs it addresses — `promo-output/`
 * is regenerated by every run and is not committed, so an edit stored there
 * would be one `bun run promo` away from being lost.
 */
const editPath = join(root, 'apps/docs-e2e/promo-cut.json');

// #region Options

const args = process.argv.slice(2);
const flag = (name: string) => args.includes(`--${name}`);
const option = (name: string, fallback: number) => {
  const hit = args.find((a) => a.startsWith(`--${name}=`));
  return hit ? Number(hit.slice(name.length + 3)) : fallback;
};

const FULL = flag('full');
/** Discard the current edit list and re-derive it from the recorded marks. */
const INIT = flag('init');
/**
 * Length of the dissolve between clips. Long enough to read as an edit, short
 * enough that no clip loses its payoff to it; `--xfade=0` gives hard cuts back.
 *
 * The overlap eats `(n-1) * XFADE` seconds off the total, so a reel runs
 * slightly shorter than the sum of its `in`/`out` spans. Only the reel
 * dissolves — `--full` stays a stream copy, which is the whole reason it can
 * concatenate five minutes of footage in seconds.
 */
const XFADE = FULL ? 0 : Math.max(0, option('xfade', 0.3));
/** Opening fade up from black and closing fade down to it. */
const BOOKEND = FULL ? 0 : 0.4;
/** Output frame size. Matches `video.size` in `playwright.promo.config.ts`. */
const [WIDTH, HEIGHT] = [1920, 1080];
/**
 * Width of the control-rail overhang the promo viewport records but never
 * delivers. Must match `RAIL` in `playwright.promo.config.ts`: the rail has to
 * stay on-page and clickable for the scenes, so it is cropped off here instead.
 */
const RAIL_PX = 312;
const FPS = 30;
/**
 * Seconds of recording that follow the last timestamp a test takes, while the
 * fixture attaches the timeline and Playwright closes and flushes the context.
 *
 * Anchoring off the end rather than the start is deliberate. The recording's
 * first frame is not written at page creation but at first paint, so the head
 * offset swings by a second or more between a trivial demo and one that loads
 * 200 rows. The teardown tail does not depend on the page at all, so
 * `duration - spanMs - TAIL_S` recovers the head for each video individually.
 *
 * Measured across scenes at ~1.85s. Only `--init` depends on it: once the edit
 * list holds real timestamps, they are used as written. If a *freshly
 * generated* list lands on the caption after the one it should show, this is
 * the number to re-measure.
 */
const TAIL_S = 1.85;

const target = join(outputDir, FULL ? 'promo-full.mp4' : 'promo-reel.mp4');

// #endregion

// #region Report shapes (only the fields we need)

interface PwAttachment {
  name: string;
  path?: string;
}
interface PwResult {
  attachments?: PwAttachment[];
}
interface PwTest {
  results?: PwResult[];
}
interface PwSpec {
  title: string;
  tests?: PwTest[];
}
interface PwSuite {
  specs?: PwSpec[];
  suites?: PwSuite[];
}

/** Mirrors `ClipMark` in `tests/promo/overlay.ts`. Only read by `--init`. */
interface ClipMark {
  label: string;
  role: 'intro' | 'feature' | 'punch' | 'outro';
  reel?: boolean;
  startMs: number;
  endMs: number;
}
interface Timeline {
  title: string;
  spanMs: number;
  marks: ClipMark[];
}

// #endregion

// #region The edit list

/** One shot: a span of one scene's recording. Array order is playback order. */
interface EditEntry {
  /** Test title, without the `@promo` tag. Matched against `report.json`. */
  scene: string;
  /** Mark-in, in seconds into that scene's `video.webm`. */
  in: number;
  /** Mark-out, in seconds into that scene's `video.webm`. */
  out: number;
  /** Free text for whoever edits the file. Printed while cutting; never rendered. */
  note?: string;
  /** Park an entry without deleting it, so its timings survive for later. */
  skip?: boolean;
}
interface EditList {
  /** Kept only so a hand-edited file explains itself. */
  $comment?: string;
  sequence: EditEntry[];
}

/** A resolved span of a source video, ready to cut. */
interface Segment {
  scene: string;
  note: string;
  video: string;
  from: number;
  to: number;
}

/** Everything the report knows about one recorded scene. */
interface Scene {
  title: string;
  video: string;
  timeline: Timeline | null;
}

// #endregion

/** Depth-first walk keeps specs in declaration order across nested describes. */
function collectSpecs(suite: PwSuite, into: PwSpec[] = []): PwSpec[] {
  for (const spec of suite.specs ?? []) into.push(spec);
  for (const child of suite.suites ?? []) collectSpecs(child, into);
  return into;
}

/**
 * ffmpeg is not a project dependency — it is only needed for this one optional
 * step. Look for it via `$FFMPEG`, on PATH, in the winget install location
 * (`winget install Gyan.FFmpeg` does NOT put it on PATH for already-open shells),
 * or as the `ffmpeg-static` package if the user chose to install it.
 */
function resolveFfmpeg(): string | null {
  if (process.env.FFMPEG && existsSync(process.env.FFMPEG)) return process.env.FFMPEG;
  const probe = spawnSync('ffmpeg', ['-version'], { stdio: 'ignore' });
  if (probe.status === 0) return 'ffmpeg';
  const winget = process.env.LOCALAPPDATA
    ? globSync(
        join(process.env.LOCALAPPDATA, 'Microsoft/WinGet/Packages/Gyan.FFmpeg*/*/bin/ffmpeg.exe').replace(/\\/g, '/'),
      )[0]
    : undefined;
  if (winget) return winget;
  const staticBin = join(root, 'node_modules/ffmpeg-static/ffmpeg.exe');
  if (existsSync(staticBin)) return staticBin;
  const staticNix = join(root, 'node_modules/ffmpeg-static/ffmpeg');
  if (existsSync(staticNix)) return staticNix;
  return null;
}

/**
 * Duration of a video, in seconds.
 *
 * Read through ffmpeg rather than ffprobe: ffprobe ships alongside ffmpeg in
 * every distribution this script looks for except `ffmpeg-static`, which
 * deliberately omits it, while `-f null -` works everywhere.
 */
function durationOf(ffmpeg: string, file: string): number {
  const probe = spawnSync(ffmpeg, ['-hide_banner', '-i', file, '-f', 'null', '-'], { encoding: 'utf8' });
  const last = [...(probe.stderr ?? '').matchAll(/time=(\d+):(\d\d):(\d\d(?:\.\d+)?)/g)].at(-1);
  if (!last) throw new Error(`could not determine the duration of ${file}`);
  return Number(last[1]) * 3600 + Number(last[2]) * 60 + Number(last[3]);
}

/**
 * Derive a first-draft edit list from the `clip()` marks the scenes recorded.
 *
 * This is a *starting point*, not the edit: every mark becomes an entry
 * spanning the full window it measured, ordered cards-first / outro-last, and
 * pre-`skip`ped where the scene opted out with `reel: false`. From then on the
 * JSON is the source of truth and this function is only reachable via `--init`.
 */
function deriveEditList(scenes: Scene[]): EditList {
  const rank = { intro: 0, feature: 1, punch: 2, outro: 3 };
  const entries: (EditEntry & { rank: number })[] = [];

  for (const scene of scenes) {
    if (!scene.timeline?.marks?.length) continue;
    const window = windowMapper(scene);
    for (const mark of scene.timeline.marks) {
      const { from, to } = window(mark);
      entries.push({
        rank: rank[mark.role],
        scene: scene.title,
        in: round(from),
        out: round(to),
        note: mark.label || `[${mark.role} card]`,
        ...(mark.reel === false ? { skip: true } : {}),
      });
    }
  }

  entries.sort((a, b) => a.rank - b.rank);
  return {
    $comment:
      'The promo edit. Array order is playback order; in/out are seconds into that scene’s video.webm. ' +
      'Edit freely — `bun run promo:stitch` reads this file as written. ' +
      '`--init` regenerates it from the recorded clip() marks and discards manual changes.',
    sequence: entries.map(({ rank: _rank, ...entry }) => entry),
  };
}

/**
 * Map a scene's recorded milliseconds onto its video's seconds.
 *
 * Both ends of the file extend past what the test measured, and only the tail
 * is predictable — see {@link TAIL_S}.
 */
function windowMapper(scene: Scene) {
  const duration = durationOf(ffmpeg, scene.video);
  const lead = scene.timeline ? duration - scene.timeline.spanMs / 1000 - TAIL_S : 0;
  return (mark: ClipMark) => {
    const from = Math.max(0, Math.min(duration, lead + mark.startMs / 1000));
    return { from, to: Math.max(from + 0.2, Math.min(duration, lead + mark.endMs / 1000)) };
  };
}

const round = (seconds: number) => Math.round(seconds * 100) / 100;

// #region Collect

if (!existsSync(reportPath)) {
  console.error(`No ${reportPath}.\nRecord the clips first:  bun run promo`);
  process.exit(1);
}

const ffmpegBin = resolveFfmpeg();
if (!ffmpegBin) {
  console.error(
    [
      'ffmpeg was not found. Install it either way:',
      '  winget install Gyan.FFmpeg      # system-wide',
      '  bun add -d ffmpeg-static        # repo-local',
    ].join('\n'),
  );
  process.exit(1);
}
// Hoisted helpers below cannot see the guard above, so re-bind it as a plain string.
const ffmpeg: string = ffmpegBin;

const report = JSON.parse(readFileSync(reportPath, 'utf8')) as { suites?: PwSuite[] };

/*
 * Scenes come from the report, not from globbing the output directory: the
 * directory names are hashed and carry no order, while the report lists specs
 * in declaration order.
 */
const scenes: Scene[] = [];
for (const suite of report.suites ?? []) {
  for (const spec of collectSpecs(suite)) {
    const attachments = spec.tests?.[0]?.results?.[0]?.attachments ?? [];
    const video = attachments.find((a) => a.name === 'video');
    if (!video?.path || !existsSync(video.path)) continue;
    const timelinePath = attachments.find((a) => a.name === 'promo-timeline')?.path;
    scenes.push({
      title: spec.title.replace(/\s*@promo\s*$/, ''),
      video: video.path,
      timeline: timelinePath && existsSync(timelinePath) ? JSON.parse(readFileSync(timelinePath, 'utf8')) : null,
    });
  }
}

if (!scenes.length) {
  console.error('The report contains no video attachments. Did the run fail before recording?');
  process.exit(1);
}

const byTitle = new Map(scenes.map((s) => [s.title, s]));
const segments: Segment[] = [];

if (FULL) {
  /*
   * Raw recordings back to back, so the head would otherwise be a demo booting
   * up. Start the recording that owns the intro card *at* the card instead of
   * prepending a copy — a prepended copy cuts back to the same card a beat
   * later, which reads as a stutter.
   */
  for (const scene of scenes) {
    const duration = durationOf(ffmpeg, scene.video);
    const intro = scene.timeline?.marks.find((m) => m.role === 'intro');
    segments.push({
      scene: scene.title,
      note: scene.title,
      video: scene.video,
      from: intro ? windowMapper(scene)(intro).from : 0,
      to: duration,
    });
  }
} else {
  if (INIT || !existsSync(editPath)) {
    const scenesWithoutClips = scenes.filter((s) => !s.timeline?.marks?.length).map((s) => s.title);
    const derived = deriveEditList(scenes);
    if (!derived.sequence.length) {
      console.error(
        'No clip() windows were recorded. Wrap each scene’s money shot in clip() — see tests/promo/overlay.ts.',
      );
      process.exit(1);
    }
    writeFileSync(editPath, `${JSON.stringify(derived, null, 2)}\n`, 'utf8');
    console.log(`${INIT ? 'Regenerated' : 'Created'} ${editPath} — ${derived.sequence.length} entries.`);
    if (scenesWithoutClips.length) {
      console.warn(`! ${scenesWithoutClips.length} scene(s) recorded no clip() and are absent from the edit:`);
      for (const scene of scenesWithoutClips) console.warn(`    ${scene}`);
    }
    // Stop after an explicit --init so the edit can be reviewed before paying
    // for an encode; an auto-created list falls through and cuts immediately.
    if (INIT) process.exit(0);
  }

  const edit = JSON.parse(readFileSync(editPath, 'utf8')) as EditList;
  const unknown = new Set<string>();
  for (const entry of edit.sequence ?? []) {
    if (entry.skip) continue;
    const scene = byTitle.get(entry.scene);
    if (!scene) {
      unknown.add(entry.scene);
      continue;
    }
    // A zero or inverted span is an editing slip, not something to render.
    if (!(entry.out > entry.in)) {
      console.warn(`! skipping "${entry.note ?? entry.scene}": out (${entry.out}) is not after in (${entry.in}).`);
      continue;
    }
    segments.push({
      scene: entry.scene,
      note: entry.note ?? '',
      video: scene.video,
      from: entry.in,
      to: entry.out,
    });
  }

  if (unknown.size) {
    console.warn(`! ${unknown.size} entr${unknown.size === 1 ? 'y' : 'ies'} name a scene that is not in the report:`);
    for (const title of unknown) console.warn(`    ${title}`);
    console.warn('  Renamed a test? Fix the "scene" field, or re-derive with --init.');
  }
}

if (!segments.length) {
  console.error(`Nothing to cut. Every entry in ${editPath} is skipped or unresolved.`);
  process.exit(1);
}

// #endregion

// #region Cut

const durations = segments.map((s) => s.to - s.from);

rmSync(workDir, { recursive: true, force: true });
mkdirSync(workDir, { recursive: true });

console.log(
  FULL
    ? `full cut: ${segments.length} scenes → ${target}`
    : `reel: ${segments.length} shots from ${editPath} → ${target}`,
);
const parts: string[] = [];

for (const [i, segment] of segments.entries()) {
  const length = durations[i];
  const from = segment.from;

  // Two-stage seek: a fast keyframe seek on the input, then an exact one on the
  // output. Input-only seeking snaps to the nearest keyframe, which in a
  // screencast can be seconds away.
  const coarse = Math.max(0, from - 3);
  const part = join(workDir, `seg-${String(i).padStart(2, '0')}.mp4`);
  // Drop the control-rail overhang the promo viewport carries — see RAIL_PX.
  const crop = `crop=in_w-${RAIL_PX}:in_h:0:0`;
  const scale = `scale=${WIDTH}:${HEIGHT}:force_original_aspect_ratio=decrease`;
  const pad = `pad=${WIDTH}:${HEIGHT}:(ow-iw)/2:(oh-ih)/2:color=#06080c`;
  const cut = spawnSync(
    ffmpeg,
    [
      '-y',
      '-v',
      'error',
      '-ss',
      coarse.toFixed(3),
      '-i',
      segment.video,
      '-ss',
      (from - coarse).toFixed(3),
      '-t',
      length.toFixed(3),
      // Normalise everything so the concat demuxer can stream-copy the parts.
      '-vf',
      `${crop},${scale},${pad},fps=${FPS},format=yuv420p`,
      '-c:v',
      'libx264',
      '-preset',
      'veryfast',
      '-crf',
      '19',
      '-an',
      part,
    ],
    { stdio: 'inherit' },
  );
  if (cut.status !== 0) process.exit(cut.status ?? 1);

  parts.push(part);
  console.log(
    `  ${String(i + 1).padStart(2)}. ${from.toFixed(2)}–${segment.to.toFixed(2)}s (${length.toFixed(2)}s)  ${segment.note}`,
  );
}

/** Hard cuts, stream-copied. Fast enough to be the only option for `--full`. */
function joinByCut(): number {
  const listPath = join(workDir, 'concat.txt');
  writeFileSync(listPath, parts.map((p) => `file '${p.replace(/\\/g, '/')}'`).join('\n'), 'utf8');
  const concat = spawnSync(
    ffmpeg,
    [
      '-y',
      '-v',
      'error',
      '-f',
      'concat',
      '-safe',
      '0',
      '-i',
      listPath,
      '-c',
      'copy',
      '-movflags',
      '+faststart',
      target,
    ],
    { stdio: 'inherit' },
  );
  if (concat.status !== 0) process.exit(concat.status ?? 1);
  return durations.reduce((sum, d) => sum + d, 0);
}

/**
 * Dissolve between clips, and open and close on black.
 *
 * `xfade` overlaps a pair at a time, so the chain has to carry a running offset
 * measured on the *composite* — each transition starts one dissolve before the
 * end of everything joined so far. The lengths are re-probed rather than taken
 * from `durations`: `-t` lands on a frame boundary, and a chain of 15 clips
 * accumulates enough rounding to drift a dissolve off its cut.
 */
function joinByDissolve(): number {
  const lengths = parts.map((p) => durationOf(ffmpeg, p));
  const chain: string[] = [];
  let stream = '0:v';
  let offset = 0;
  for (let i = 1; i < parts.length; i++) {
    offset += lengths[i - 1] - XFADE;
    chain.push(`[${stream}][${i}:v]xfade=transition=fade:duration=${XFADE}:offset=${offset.toFixed(3)}[x${i}]`);
    stream = `x${i}`;
  }
  const total = offset + lengths[lengths.length - 1];
  chain.push(`[${stream}]fade=t=in:st=0:d=${BOOKEND},fade=t=out:st=${(total - BOOKEND).toFixed(3)}:d=${BOOKEND}[v]`);

  const render = spawnSync(
    ffmpeg,
    [
      '-y',
      '-v',
      'error',
      ...parts.flatMap((p) => ['-i', p]),
      '-filter_complex',
      chain.join(';'),
      '-map',
      '[v]',
      '-c:v',
      'libx264',
      '-preset',
      'veryfast',
      '-crf',
      '19',
      '-pix_fmt',
      'yuv420p',
      '-an',
      '-movflags',
      '+faststart',
      target,
    ],
    { stdio: 'inherit' },
  );
  if (render.status !== 0) process.exit(render.status ?? 1);
  return total;
}

const runtime = XFADE > 0 && parts.length > 1 ? joinByDissolve() : joinByCut();

console.log(`\n${target}  —  ${runtime.toFixed(1)}s`);
if (!FULL) console.log(`Retime or reorder it in ${editPath}, then re-run — no need to re-record.`);

// #endregion
